defaults:
  - _self_
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

db:
  postgres_connection_string: postgresql://postgres:postgres@localhost:5438/math_ir

bronze_schema_prefix: debug_bronze
silver_schema_prefix: debug_silver

bronze_load_formulas: true
bronze_load_posts: true

silver_load_formulas: true
silver_load_posts: true

paths:
  raw_dir: DEBUG/data_arqmath/formulas
  posts_path: DEBUG/data_arqmath/posts/posts.xml

formula_sources:
  - table: latex_arqmath
    dir: ${paths.raw_dir}/latex_representation_v3
  - table: slt_arqmath
    dir: ${paths.raw_dir}/slt_representation_v3
  - table: opt_arqmath
    dir: ${paths.raw_dir}/opt_representation_v3

post_sources:
  - table: post_arqmath
    path: ${paths.posts_path}

silver_formula:
  latex_table: latex_arqmath
  p_mathml_table: slt_arqmath
  c_mathml_table: opt_arqmath

silver_post:
  post_table: post_arqmath
