defaults:
  - _self_
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

db:
  postgres_connection_string: postgresql://postgres:postgres@localhost:5438/math_ir

paths:
  raw_dir: data/raw
